### ISSUE TITLE
Rename sub-modules to follow parent_child  Drupal conventions

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_elections#11]
See discussion on 
https://github.com/localgovdrupal/localgov_elections_reporting/issues/62

@dedavidson @markconroy I'm really keen to make sure these sub-modules are named following the convention:

`[parent_module_name]_[sub_module_name]`

As far as I can find, this is a convention rather than a standard, but it makes a lot of sense to avoid namespace conflicts and @ekes confirmed this as expected naming conventions when we touched on it in Merge Tuesday today.

Happy to help do this and test this rapidly if we can.

_Originally posted by @finnlewis in https://github.com/localgovdrupal/localgov_elections_reporting/issues/62#issuecomment-2176116962_

**Comment by finnlewis** [comment]
Discussing in our meeting.

The current modules that will need re-writing are: 

 - localgov_elections_ons_twenty_three_wards
 - localgov_elections_constituency_provider

But @markconroy pointed out that if we rename the parent module to localgov_elections, that would also cover it.

Further to this, @stephen-cox mentioned we wanted to look at renaming field names and content types to follow suit with localgov_ prefixes.

Agreed to try setting up another project called localgov_elections and attempt the rename there.

This way we can keep the namespace here for anyone testing it and release a beta there.

I will make a start on this now.

**Comment by willguv** [comment]
Thanks for doing this @finnlewis

**Comment by markconroy** [comment]
Work for this is being done at https://github.com/localgovdrupal/localgov_elections/pull/2

**Comment by markconroy** [comment]
We can close this, I think?
