### ISSUE TITLE
Chart issues on mobile

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#110]
When viewing https://new.newcastle.gov.uk/election/uk-parliamentary-general-election-4-july-2024 and https://new.newcastle.gov.uk/election/uk-parliamentary-general-election-4-july-2024/cramlington-killingworth on mobile, there are two issues:

1) The charts show incorrect info as some rows are missing

![Image](https://github.com/user-attachments/assets/52658dd0-fc92-4f43-b090-c84c6737ce1c)

If this can't be fixed easily, it may be better to not show the chart on mobile

2) When resizing the page, the chart does not automatically resize

![Image](https://github.com/user-attachments/assets/dba16d1a-ad0a-48d5-9386-ec92dd10543a)

**Comment by markconroy** [comment]
- I have a PR to fix the first item here: #124 
- I have a follow-up for the second issue here: https://github.com/localgovdrupal/localgov_elections/issues/125
