### ISSUE TITLE
Votes cast needs to include rejected ballots

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#113]
On https://new.newcastle.gov.uk/election/uk-parliamentary-general-election-4-july-2024/cramlington-killingworth, we need to check that the "Votes cast" includes the "Rejected ballot papers"

I think this is fixed already, can you confirm

**Comment by dedavidson** [comment]
@willguv this was fixed https://github.com/localgovdrupal/localgov_elections/issues/103

**Comment by willguv** [comment]
Thanks @dedavidson
