### ISSUE TITLE
Missing sidebar and duplicated titles on some pages

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#116]
This may be a Newcastle/ old version issue btu we should check it

https://new.newcastle.gov.uk/node/936/electoral-map
https://new.newcastle.gov.uk/node/936/results

The urls are an incorrect format too, so this suggests they're using an older version of elections

**Comment by markconroy** [comment]
I've given this a good testing and it seems to be an issue with the older version of the module. I remember having the sidebar blocks missing once or twice when installing this but clearing the cache always seemed to have sorted it.

**Comment by willguv** [comment]
Thanks @markconroy 

Copying @Mjeffbrown

**Comment by Mjeffbrown** [comment]
Thanks @willguv / @markconroy. We'll get our module updated.
