### ISSUE TITLE
Don't load font awesome from module

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_elections#14]
Are we sure we definitely need to load the whole of font awesome? 

I've a feeling we are only using one or two icons from the library in this module, so it is probably better to include them as SVGs in the module.

Even better, we can use the icons from the `localgov_base` icons directory. The templates coming with the module should be very much bare bones "just enough to get you going" and we can have more fully-fleshed out ones in the `localgov_base` theme so all these can share/use the icon set from there.

**Comment by dedavidson** [comment]
I agree, we don't need the whole of font awesome. Only two icons are used.

- PDF `fa-solid fa-file-pdf` in the electoral candidates view when a PDF file is uploaded
- Right arrow `fa-solid fa-chevron-right` in the election menu block template
