### ISSUE TITLE
Investigate and update dependencies

### ISSUE THREAD

**Issue by chriswales95** [localgovdrupal/localgov_elections#22]
Two points we need to look at.

1. There are likely dependencies we no longer need e.g. autocomplete_deluxe and perhaps paragraphs_table. It would be good to do a sweep and remove things we don't need to avoid bloated installs.
2. We need to look at if we should depend on localgov base modules as suggested by @finnlewis.

**Comment by markconroy** [comment]
Let's also look at using the stable version of the charts module

**Comment by millnut** [comment]
@chriswales95 any update on using the stable version of the `drupal/charts` module, we shouldn't ship a stable release of elections until this is resolved

**Comment by chriswales95** [comment]
Hi @millnut, unfortunately not. Things have been busy and we haven't had a chance to get to this one yet. I might be able to have a go soon.

**Comment by markconroy** [comment]
PR attached ^
