### ISSUE TITLE
Automate URL alias for subpages

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_elections#29]
At the moment, election subpages are accessed from URLs like /node/1234/results, /node/1234/candidates, /node/1234/electoral-map, /node/1234/share, etc. from the [Elections menu block](https://www.cumberland.gov.uk/election/cumberland-council-election-5-may-2022).  We can manually add URL aliases to improve this. But it would be better to automate this.

Raising this at Will's suggestion.  Copying @willguv @finnlewis @dedavidson @chriswales95

**Comment by Adnan-cds** [comment]
I tried writing a [Pathauto alias plugin](https://git.drupalcode.org/project/pathauto/-/blob/8.x-1.x/src/AliasTypeInterface.php?ref_type=heads) for this but haven't had much luck :(

**Comment by dedavidson** [comment]
I have a fix for this

**Comment by willguv** [comment]
Nice one @dedavidson thank you

**Comment by markconroy** [comment]
Is this issue fixed? The attached PR for it is now closed, but I'm not sure the actual issue itself is resolved.

**Comment by dedavidson** [comment]
No, the PR didn't work. So we need to use a different approach which creates/deletes the aliases when saving/deleting the election nodes using hooks or events.

**Comment by chriswales95** [comment]
Working on this. Looks like the most straightforward way is to generate the aliases manually.
