### ISSUE TITLE
Question: PDF added to Areas not appearing anywhere

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_elections#36]
Hello,
We have added a PDF file to an *Area vote* node.  But we can't find this PDF appearing anywhere :(  Have we missed anything?  Thanks.

Copying @dedavidson

**Comment by chriswales95** [comment]
@Adnan-cds Seems to work for me. It should pop up as an item in the left-hand menu.
<img width="1134" alt="image" src="https://github.com/localgovdrupal/localgov_elections/assets/43383145/e223ac4d-418f-47f4-9cb4-b2b924293cce">

Are you certain the area vote has the PDF uploaded? The item seems to only be set to appear if at least one area vote has a PDF.

**Comment by Adnan-cds** [comment]
Ah.. sorry, yes.  I can see the PDF link now.  I didn't realize it will appear in the "Electoral candidates" page.  I have [proposed](https://github.com/localgovdrupal/localgov_elections/pull/38) a small update to the documentation.
