### ISSUE TITLE
Deleted party causes WSOD

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_elections#37]
Reproduction steps:
1. Added a few new parties.
2. Added a new election.
3. Attached the parties from step 1 to the election from step 2.
4. Election page loads okay.
5. Deleted one or more parties from step 1.
6. Attempts to reload the election page results in WSOD (White screen of death) :(

**Comment by Adnan-cds** [comment]
Copying @DavidBAsch

**Comment by chriswales95** [comment]
@Adnan-cds I don't suppose you have a stacktrace handy? If not one of us can just follow the steps.

**Comment by Adnan-cds** [comment]
Sorry, should have provided the error message from the log: `Error: Call to a member function get() on null in Drupal\localgov_elections_reporting\Plugin\views\field\WardParty->render() (line 44 of /var/www/html/web/modules/contrib/localgov_elections_reporting/src/Plugin/views/field/WardParty.php).`

**Comment by dedavidson** [comment]
Parties shouldn't be deleted as they may be needed from a historical point of view. We had planned to remove the party taxonomy and encapsulate the parties within the election content type so that each election node was completely standalone. We didn't have the time to do this.

**Comment by Adnan-cds** [comment]
> Parties shouldn't be deleted as they may be needed from a historical point of view.

Removing parties may be needed sometimes during testing and training.  That's how we stumbled upon it :(

**Comment by dedavidson** [comment]
Probably need to add a hook to prevent deletion if tied to a candidate in an areas node

**Comment by finnlewis** [comment]
@Adnan-cds thinks it's easy enough to add an if to catch this.
