### ISSUE TITLE
Summary page still showing all parties

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#40]
Summary page still showing all parties even though there are not candidates for them

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/3bbbc647-a593-486e-bc0b-6799ef5d5ccc)

This has been fixed before, is there an open PR? Feel free to delete this if so

**Comment by snpower** [comment]
I can't reproduce this issue either.

**Comment by willguv** [comment]
Fixed with a fresh install
