### ISSUE TITLE
Previous winner needs a taxonomy item to work

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#41]
Previous winner requires a taxonomy term to work. Think plain text should be enough

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/838e8bb5-d895-42ac-bf30-b601dff0bca7)

**Comment by dedavidson** [comment]
@willguv it should be the party of the previous winner not a candidate. That said plain text will work.

**Comment by markconroy** [comment]
I like the idea of taxonomy term here, so we have the extra data around party name, colours, etc. And it makes sure we don't have people spelling Labor in one election and Labour in another.

Maybe we could change the field label to 'Previous winning party'?

**Comment by willguv** [comment]
Yes think it needs 'Previous winning party' as a label @markconroy 

Probably doesn't need the helper text with this change

Could you do a PR for that? Many thanks

**Comment by markconroy** [comment]
PR: https://github.com/localgovdrupal/localgov_elections/pull/55
