### ISSUE TITLE
Dev package used in composer.json

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_elections#50]
Similar to https://github.com/localgovdrupal/localgov_directories/issues/381, we are using a dev package `"drupal/charts": "^5.0.x-dev@dev"`  this should be locked to a commit hash or using a stable release.

**Comment by markconroy** [comment]
I wonder why we are using a dev version in the first place? Maybe the latest stable release is good enough for us, which was released on April 24th - 5.0.13.

**Comment by millnut** [comment]
Hi @chriswales95 do you know why the dev version of `drupal/charts` is used instead of the stable release?

**Comment by dedavidson** [comment]
It is likely historical from the original incarnation of the module.

**Comment by chriswales95** [comment]
@millnut Yeah, @dedavidson is likely right. 

There is another issue regarding dependencies already https://github.com/localgovdrupal/localgov_elections/issues/22. So I think we can close this one.
