### ISSUE TITLE
Get Chartjs to show integers instead of decimals

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_elections#53]
The bottom of our bar graphs go from 0.1 to 1.0. Can we change these to show integers instead?

<img width="1256" alt="342914315-5f97e72d-792e-480f-b4f1-d926a12d2042" src="https://github.com/localgovdrupal/localgov_elections/assets/2183332/988ec25d-a21c-4792-8df3-e65f203ece96">

**Comment by markconroy** [comment]
I think the issue here is that in the original screeshot, there was only 1 vote cast. If you add thousands of votes, the number are better, see here:
![Screenshot 2024-07-02 at 12 59 24](https://github.com/localgovdrupal/localgov_elections/assets/2183332/59504cfd-a25b-4861-a403-19ffc25eb5ce)

**Comment by willguv** [comment]
This is a lot better, thanks Mark - have you implemented it?

**Comment by markconroy** [comment]
There's nothing to implement, this is out of the box. The reason you see 0.1 and 0.2 in the original screenshot is because there was only 1 vote cast.
