### ISSUE TITLE
Share of the vote is misleading

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#57]
An issue for councils running more than one constituency election

The share of the vote page totals up all the votes across all constituencies - it doesn't show a vote share in each constituency

People are used to seeing vote shares in each individual constituency, so it's confusing. Possible solutions:

- Change the label to 'Overall vote share across [names of constituencies] so it's clear what is being shown
- Keep the vote share page, and show a table for each constituency
- PREFERRED Drop the vote share page, and show vote share on each of the constituency result pages. Page could be organised as follows:

h2 - [area name]

[result block] (eg 'Conservative HOLD')

h2 - Votes cast

[bar chart]
[vote share table]

h2 - Analysis

[analysis table]

### To replicate

- Set up a single election
- Add two areas, with candidates and votes for each
- Visit the share of the vote page for either of them
- See the total votes cast across both constituencies

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/a8524340-49dc-408c-8a99-909ef1dc653e)

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/a3fd9070-468a-4978-8a29-b516e31761c4)

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/6f40032b-24eb-4375-83b1-bff3228819f4)

**Comment by willguv** [comment]
@dedavidson @finnlewis @markconroy would be great to get tour thoughts on this and size it please - cheers

**Comment by dedavidson** [comment]
I think this page should be kept. It is there by design. Particularly in a council election people like to see the share of the vote across the while council. I think just added "Overall" to it would be sufficient.

**Comment by willguv** [comment]
How about this:

Share of the vote page

- change the title to "Overall vote share" so it makes more sense for council elections
- hide this page for the national parliamentary type

Areas vote page

- include vote share between the votes cast and analysis blocks. H2 is "Vote share"

**Comment by willguv** [comment]
@dedavidson any thoughts please?

**Comment by dedavidson** [comment]
That sounds like a plan.

**Comment by willguv** [comment]
Thanks 

@markconroy sonething you could look at early next week please?

**Comment by markconroy** [comment]
Yep, I'll try get to it on Monday.

**Comment by willguv** [comment]
Thanks @markconroy I've rewritten the plan above so it's a bit more clear

https://github.com/localgovdrupal/localgov_elections/issues/57#issuecomment-2193946889

**Comment by finnlewis** [comment]
Are you working on this one @markconroy ?

**Comment by markconroy** [comment]
PR to change title to 'Overall vote share': https://github.com/localgovdrupal/localgov_elections/pull/80

PR for the rest of it: https://github.com/localgovdrupal/localgov_elections/pull/81 (not working yet - I'm lost)

**Comment by markconroy** [comment]
@finnlewis I'm happy to co-work with someone on it, I don't think I can fully figure out what I need to do

**Comment by willguv** [comment]
@markconroy want to chat about it today?

**Comment by finnlewis** [comment]
Discussing in Merge Tuesday: 

@willguv agrees that for initial release: 
  - remove share of the vote from the overall (ideally just for the national parliamentary election type of election) 

We can then follow up with another issue to add the share of the vote to areas.

**Comment by finnlewis** [comment]
@chriswales95 will take a look after lunch!
