### ISSUE TITLE
Change 'Election summary' heading

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#60]
On summary pages the bar chart isn't that clear

It would make more sense if the heading "Election summary" is changed to "Seats won"

I think that title is applicable regardless of the election type. In local elections councillors also win seats

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/66ed4986-49af-4d30-8f34-1c7a3443b25a)

**Comment by dedavidson** [comment]
Agree
