### ISSUE TITLE
Remove majority count from national parliamentary elections

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#61]
On the summary page, the "Overall majority required: " info is not needed for national parliamentary elections

It should be hidden for this type 

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/24e82c48-03cb-42b1-adfd-787b91631914)

**Comment by dedavidson** [comment]
There is already a tick box for disabling the majority count for any election. The logic for that could be amended to override if the type is set to National Parliamentary.

**Comment by willguv** [comment]
I totally missed that, sorry Duncan. Yes think it's a good idea to switch off for this election type

**Comment by markconroy** [comment]
PR here: https://github.com/localgovdrupal/localgov_elections/pull/79

However, I think the checkbox should be enough and we shouldn't need to be so forceful, especially given in some countries we might want to show the majority field for national elections.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by markconroy** [comment]
New PR for this, to set "Show majority" to "Off" by default.
https://github.com/localgovdrupal/localgov_elections/pull/83
