### ISSUE TITLE
Change title on areas vote pages

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#63]
On areas vote pages:

- the area name is repeated at the top of the page. It's noise that users don't need
- we generally don't use compound titles for pages [section hyphen page name]

It would be better to use:

[election] for the h1

[area name] for the h2

In the example:

"GE 2019" for the h1

"Bexhill and Battle" for the h2

![Image](https://github.com/localgovdrupal/localgov_elections/assets/708140/08873f15-f085-4571-a6b8-005a1ce6fc91)

**Comment by dedavidson** [comment]
I agree the noise is confusing but this would still be confusing with the breadcrumbs having the Election in them. I would have [area name] for H1, "Share of vote" or similar for the H2.

**Comment by willguv** [comment]
I suggested something on https://github.com/localgovdrupal/localgov_elections/issues/57 that could work here

h1 - [area name]

[result block] (eg 'Conservative HOLD')

h2 - Votes cast

[bar chart]
[vote share table - still think this would be good here]

h2 - Analysis

[analysis table]

**Comment by willguv** [comment]
Thoughts on this please @dedavidson?

**Comment by dedavidson** [comment]
Unless it is a typo, you can't have the H1 lower in the hierarchy than an H2. You have to have an initial H1 for accessibility

**Comment by willguv** [comment]
Sorry it was a typo - fixed now

**Comment by dedavidson** [comment]
This is good only suggestion would be to have an H2 between bar chart and vote share

**Comment by willguv** [comment]
How's this?

> h1 - [area name]
> 
> [result block] (eg 'Conservative HOLD')
>
> h2 - Votes cast
>
> [bar chart]
>
> h2 - Vote share 
>
> [vote share table]
>
> h2 - Analysis
>
> [analysis table]

Would you be able to do it, or shall I ask Mark if he has time? Whatever's best for you

**Comment by dedavidson** [comment]
That looks good. I'm tight for time so best ask Mark

**Comment by markconroy** [comment]
PR created #71 

Here's how it looks now (I made a few changes to spacing and layout as well):

![Screenshot 2024-06-28 at 14 50 26](https://github.com/localgovdrupal/localgov_elections/assets/2183332/34924764-f7da-47bd-9278-c734d9ebc5d0)

**Comment by willguv** [comment]
This looks great, thanks Mark!!
