### ISSUE TITLE
Election summary page is using a hardcoded label for results

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_elections#72]
The Election summary page is using a [hardcoded label](https://github.com/localgovdrupal/localgov_elections/blob/2bbeb610f133c71bf01a22ad062867f0d3eb3c30/config/install/views.view.localgov_election_results.yml#L1377) for results.

How to reproduce:
- Create a National Parliamentary election.
- Open the summary page of this new election.
- Look for the results.
- The results heading says "Ward results".

**Comment by willguv** [comment]
Nice one @Adnan-cds - thank you!
