### ISSUE TITLE
"Add area" button appears despite user permissions

### ISSUE THREAD

**Issue by chriswales95** [localgovdrupal/localgov_elections#73]
The add area local tasks appear even if logged in or if you don't have correct permission. 

PR incoming.

**Comment by willguv** [comment]
Hi @chriswales95 how are you getting in with this please? Thanks

**Comment by chriswales95** [comment]
HI @willguv, it was closed by #74 so should be already done.

**Comment by willguv** [comment]
Cheers @chriswales95 !
