### ISSUE TITLE
Tidy up 'Add content' menu

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#8]
Currently the 'Election' content type sits at the top level of the 'Add content' menu

It needs to be moved to the 'Election' folder to sit alongside 'Areas vote'

See screenshot

<img width="580" alt="Screenshot 2024-06-20 at 12 52 50" src="https://github.com/localgovdrupal/localgov_elections/assets/708140/c0bb0648-4a8f-4d5c-8f70-b19390bd8799">

**Comment by dedavidson** [comment]
This is optional config - https://github.com/localgovdrupal/localgov_elections_reporting/pull/52
