### ISSUE TITLE
Changing data after finalised is impacting the result.

### ISSUE THREAD

**Issue by dedavidson** [localgovdrupal/localgov_elections#88]
A council has reported this issue while testing 

"gone in and added a figure for spoilt ballot papers in an area, and it has removed the original winner from the results and now has another party as the winning party. I get the impression that we need to type everything in right the first time before ticking that "Votes finalised" box, because if we have to go back in and amend something it is affecting the display."

I've not had a chance to test yet.

**Comment by finnlewis** [comment]
Possibly related: editing the results of an area does not allow me to save.

Steps to reproduce: 

1. Install fresh localgov profile, 
2. enable localgov_elections_demo_content, 
3. edit an area (eg https://localgov.ddev.site/node/2/edit) and amend the vote count for one of the results, save.
4. Error message: The referenced entity (taxonomy_term: demo content) does not exist.
5. And I cannot save the area.

Tried toggling the finalised votes to off too. Same behaviour.

**Comment by chriswales95** [comment]
@finnlewis Will open up another issue for yours.

**Comment by dedavidson** [comment]
Closing in favour of #94
