### ISSUE TITLE
Only show parties with candidates assigned

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections#9]
On installing Elections for the first time, users are presented with a summary page showing every party

<img width="694" alt="Screenshot 2024-06-20 at 12 51 51" src="https://github.com/localgovdrupal/localgov_elections/assets/708140/81b7255c-512e-437c-a6e8-a21148281ae0">

The summary page should only list parties where there are candidates assigned

**Comment by dedavidson** [comment]
Fixed by https://github.com/localgovdrupal/localgov_elections/issues/27
